// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type CommitOrderRequest struct {
	Platform       int8          `json:"platform"` // 平台 0柠檬树 1牧云
	CommitRoomList []*CommitRoom `json:"commitRoomList"`
}

type CommitOrderResponse struct {
	Result []*CommitRoomResult `json:"result"`
}

type CommitRoom struct {
	RoomStartDate string `json:"roomStartDate"`
	RoomEndDate   string `json:"roomEndDate"`
	RoomId        string `json:"roomId"`
	RoomName      string `json:"roomName"`
}

type CommitRoomResult struct {
	RoomId     string `json:"roomId"`
	RoomName   string `json:"roomName"`
	Success    bool   `json:"success"`
	FailReason string `json:"failReason"`
}

type Empty struct {
}

type GetRoomListRequst struct {
	Platform      int8   `json:"platform"` // 平台 0柠檬树 1牧云
	RoomStartDate string `json:"roomStartDate"`
	RoomEndDate   string `json:"roomEndDate"`
}

type GetRoomListResponse struct {
	RoomList []*Room `json:"roomList"`
}

type Job struct {
	JobId    string      `json:"jobId"`
	Room     *CommitRoom `json:"room"`
	Interval int32       `json:"interval"`
	Platform int8        `json:"platform"`
}

type OperateJobListRequest struct {
}

type OperateJobListResponse struct {
	List []*Job `json:"list"`
}

type OperateJobRequest struct {
	Operate  string      `json:"operate"` // 操作类型 add delete
	JobId    string      `json:"jobId,optional"`
	Platform int8        `json:"platform,optional"`
	Interval int32       `json:"interval,optional"` //间隔时间 单位秒
	Room     *CommitRoom `json:"room,optional"`
}

type RefreshTokenRequest struct {
	Platform int8   `json:"platform"` // 平台 0柠檬树 1牧云
	Token    string `json:"token"`
}

type RefreshTokenResponse struct {
	Token string `json:"token"`
}

type Room struct {
	RoomId   string `json:"roomId"`
	RoomName string `json:"roomName"`
}
