// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type CommitOrderRequest struct {
	Platform       int8          `json:"platform"` // 平台 0柠檬树 1牧云
	CommitRoomList []*CommitRoom `json:"commitRoomList"`
}

type CommitOrderResponse struct {
	Result []*CommitRoomResult `json:"result"`
}

type CommitRoom struct {
	RoomStartDate string `json:"roomStartDate"`
	RoomEndDate   string `json:"roomEndDate"`
	RoomId        string `json:"roomId"`
	RoomName      string `json:"roomName"`
}

type CommitRoomResult struct {
	RoomId   string `json:"roomId"`
	RoomName string `json:"roomName"`
	Success  bool   `json:"success"`
}

type GetRoomListRequst struct {
	Platform      int8   `json:"platform"` // 平台 0柠檬树 1牧云
	RoomStartDate string `json:"roomStartDate"`
	RoomEndDate   string `json:"roomEndDate"`
}

type GetRoomListResponse struct {
	RoomList []*Room `json:"roomList"`
}

type Room struct {
	RoomId   string `json:"roomId"`
	RoomName string `json:"roomName"`
}
