// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"camp/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 提交订单
				Method:  http.MethodPost,
				Path:    "/commitOrder",
				Handler: CommitOrderHandler(serverCtx),
			},
			{
				// 获取房间列表
				Method:  http.MethodPost,
				Path:    "/list",
				Handler: GetRoomListHandler(serverCtx),
			},
			{
				// 操作任务
				Method:  http.MethodPost,
				Path:    "/operateJob",
				Handler: OperateJobHandler(serverCtx),
			},
			{
				// 获取任务列表
				Method:  http.MethodPost,
				Path:    "/operateJobList",
				Handler: OperateJobListHandler(serverCtx),
			},
			{
				// 刷新token
				Method:  http.MethodPost,
				Path:    "/refreshToken",
				Handler: RefreshTokenHandler(serverCtx),
			},
		},
	)
}
